name: Run unit tests with Python

on: [push]

jobs:
    build:
       runs-on: ubuntu-latest

       steps:
        - uses: actions/checkout@v2
        - name: Run script
          run: |
             ls -la 
             pwd
             python3 logic.py
             mkdir -p aaa

        - name: Check run
          run: |
              pwd
              ls 
   test:
       needs: build
       runs-on: ubuntu-latest

       steps:
          - uses: actions/checkout@v2
            with:
              repository: Airbnb
          - name: aaaaa
            run: | 
              echo "aaaaa"
              ls -la
              pwd

