name: Run unit tests with Python

on: [push]

jobs:
   build:
       runs-on: ubuntu-latest

       strategy:
            matrix:
        
                python-version: [3.7, 3.8]

       steps:
        - name: Print messages
          run: |
              echo "Hello World!"
        - name: Run script
          run: |
              python3 logic.py
