name: Run unit tests with Python

on: [push]

jobs:
    build:
       runs-on: ubuntu-latest

       steps:
        - uses: actions/checkout@v2
        - name: Run script
          run: |
             ls -la 
             pwd
             python3 logic.py
             mkdir -p aaa

        - name: Check run
          run: 
              pwd
    test:
        needs: build
        runs-on: ubuntu-latest

        steps:
           - uses: actions/download-artifact@v2
           - name: aaaaa
             run: | 
               echo "aaaaa"
               ls -la
               pwd

